name: Issue Video Background Removal Trigger

on:
  issues:
    types: [opened]

jobs:
  parse-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show input summary
        run: |
          echo "@create-video-remove-bg"
          echo "プロンプト: 猫が公園で遊んでいる様子"
          echo "背景色: transparent (オプション: transparent/white/black/green)"
